# Reeglid

## Asukoha vektor

```{=tex}
\begin{align}
\vec{r} := x \cdot \vec{i} + y \cdot \vec{j} + z \cdot \vec{k},
(\#eq:r)
\end{align}
```

kus $x$, $y$ ja $z$ on Descartes'i ruumi koordinaadid `r render_with_emojis("((ref:haynes-2014-crc), p. 2-1)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{L},
(\#eq:dimensional-analysis-for-r)
\end{align}
```

mistõttu ühik on $m$.


## Kiiruse vektor

```{=tex}
\begin{align}
\vec{v} := \frac{\mathrm{d}(\vec{r})}{\mathrm{d}(t)},
(\#eq:v)
\end{align}
```

kus $\vec{r}$ on asukoha vektor ja *t* on kestus `r render_with_emojis("((ref:haynes-2014-crc), p. 2-1)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L}{T}},
(\#eq:dimensional-analysis-for-v)
\end{align}
```

mistõttu ühik on $\frac{m}{s}$.


## Kiirenduse vektor

```{=tex}
\begin{align}
\vec{a} := \frac{\mathrm{d}(\vec{v})}{\mathrm{d}(t)},
(\#eq:a)
\end{align}
```

kus $\vec{v}$ on kiiruse vektor ja *t* on kestus `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L}{T}}{T} = \frac{L}{T^2}},
(\#eq:dimensional-analysis-for-a)
\end{align}
```

mistõttu ühik on $\frac{m}{s^2}$.

## Jõud

```{=tex}
\begin{align}
\vec{F} := m \cdot \vec{a},
(\#eq:force)
\end{align}
```

kus *m* on mass ja $\vec{a}$ on kiirenduse vektor `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{M \cdot \frac{L}{T^2} = \frac{L \cdot M}{T^2}},
(\#eq:dimensional-analysis-for-force)
\end{align}
```

mistõttu ühik on $\frac{m \cdot kg}{s^2}$ või lühemalt $N$.

## Elektromotoorjõud

> Allikast tarnitud energia jagatud läbi allika transporditava laenguga.

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-51.)")`

```{=latex}
\begin{align}
E := \int{\frac{\vec{F}}{Q}} \cdot \mathrm{d}(s),(\#eq:emf) 
\end{align}

```

milles *Q* on elektrilaeng `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")` ja $s$ on tee pikkus `r render_with_emojis("((ref:haynes-2014-crc), p. 2-1)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L \cdot M}{T^2}}{I \cdot T} \cdot L = \frac{L^2 \cdot M}{I \cdot T^3}}
(\#eq:dimensional-analysis-for-emf)
\end{align}
```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-49; (ref:newell-sp), p. 31)")`, mistõttu ühik on $\frac{m^2 \cdot kg}{A \cdot s^3}$ või lihtsamalt $\frac{m^2 \cdot kg}{C \cdot s^2}$ või lühemalt $\frac{m \cdot N}{C}$ või veel lühemalt $\frac{J}{C}$ või kõige lühemalt $V$ `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`.

Avaldan valemist \@ref(eq:emf) jõu:

```{=latex}
\begin{align}
\vec{F} := \frac{E \cdot Q}{\mathrm{d}(s)}.(\#eq:F-via-E-Q-s) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{I \cdot T^3} \cdot I \cdot T}{L} = \frac{L^2 \cdot M \cdot I \cdot T}{I \cdot T^3 \cdot L} = \frac{L \cdot M}{T^2}},
(\#eq:dimensional-analysis-for-F-via-E-Q-s)
\end{align}
```

mistõttu ühik on $\frac{m \cdot kg}{s^2}$ ehk lihtsamalt $N$.

## Elektrivool

```{=latex}
\begin{align}
I := \frac{\mathrm{d}(Q)}{\mathrm{d}(t)},(\#eq:I) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-3)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{I \cdot T}{T} = I},
(\#eq:dimensional-analysis-for-I)
\end{align}
```

mistõttu ühik on $A$.

## Töö

```{=latex}
\begin{align}
W := \int{\vec{F}} \cdot \mathrm{d}(s)(\#eq:W) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L \cdot M}{T^2} \cdot L = \frac{L^2 \cdot M}{T^2}},
(\#eq:dimensional-analysis-for-W)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^2}$ või lühemalt $m \cdot N$ või kõige lühemalt $J$.

Asendan valemisse \@ref(eq:W) jõu valemist \@ref(eq:F-via-E-Q-s) leheküljel`r render_pageref("eq:F-via-E-Q-s")`:

```{=latex}
\begin{align}
W := \int{\overrightarrow{\frac{E \cdot Q}{\mathrm{d}(s)}}} \cdot \mathrm{d}(s) = E \cdot Q.(\#eq:W-via-E-Q) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L^2 \cdot M}{I \cdot T^3} \cdot I \cdot T = \frac{L^2 \cdot M}{T^2}},
(\#eq:dimensional-analysis-for-W-via-E-Q)
\end{align}
```

millest johtuvalt on ühik $\frac{m^2 \cdot kg}{s^2}$ ehk lühemalt $m \cdot N$ ehk kõige lühemalt $J$.

## Elektriline potentsiaal

```{=latex}
\begin{align}
V := \frac{\mathrm{d}(W)}{\mathrm{d}(Q)},(\#eq:V) 
\end{align}

```

milles $W$ on töö `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{T^2}}{I \cdot T} = \frac{L^2 \cdot M}{T^2 \cdot I \cdot T} = \frac{L^2 \cdot M}{T^3 \cdot I}},
(\#eq:dimensional-analysis-for-V)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{A \cdot s^3}$ või kõige lühemalt $V$.

## Elektripotentsiaalide erinevus

Elektripotentsiaalide erinevus on ühtlasi pingelang.

```{=latex}
\begin{align}
U := V_2 - V_1,(\#eq:U) 
\end{align}

```

milles $V_1$ ja $V_2$ on elektrilised potentsiaalid `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L^2 \cdot M}{T^3 \cdot I}},
(\#eq:dimensional-analysis-for-U)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{A \cdot s^3}$ või kõige lühemalt $V$.

## Elektritakistus

```{=latex}
\begin{align}
R := \frac{U}{I},(\#eq:R) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-3)")`, milles *U* on elektripotentsiaalide erinevus `r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{T^3 \cdot I}}{I} = \frac{L^2 \cdot M}{T^3 \cdot I^2}},
(\#eq:dimensional-analysis-for-R)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{A^2 \cdot s^3}$ või lühemalt $A \cdot V$ või kõige lühemalt $\Omega$.

## Terminali elektripotentsiaalide erinevus

```{=latex}
\begin{align}
U_\mathrm{klemm} := E - I \cdot R_\mathrm{sisemine},(\#eq:V-klemm) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-1)")`, milles *I* on elektrivool ja $R_\mathrm{sisemine}$ on sisemine elektritakistus `r render_with_emojis("((ref:haynes-2014-crc), p. 2-3)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L^2 \cdot M}{I \cdot T^3}},
(\#eq:dimensional-analysis-for-V-klemm)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{A \cdot s^3}$ või kõige lühemalt $V$.

Kirjutades valemis \@ref(eq:V-klemm) klemmipinge lahti kasutades valemit \@ref(eq:R), saab avaldada voolutugevuse takistuste ja elektromotoorjõu kaudu:

```{=latex}
\begin{align}
I \cdot R &= E - I \cdot R_\mathrm{sisemine}\\
I \cdot R + I \cdot R_\mathrm{sisemine} &= E\\
I \cdot (R + R_\mathrm{sisemine}) &= E\\
I :&= \frac{E}{R + R_\mathrm{sisemine}}.(\#eq:I-E-R) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{I \cdot T^3}}{\frac{L^2 \cdot M}{T^3 \cdot I^2}} = I},
(\#eq:dimensional-analysis-for-I-E-R)
\end{align}
```

mistõttu ühik on $A$.

## Võimsus

```{=latex}
\begin{align}
P := \frac{\mathrm{d}(W)}{\mathrm{d}(t)}(\#eq:P-via-W-t) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{T^2}}{T} = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-via-W-t)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^3} = \frac{N \cdot m}{s} = \frac{J}{s} = W$.

Asendan valemisse \@ref(eq:P-via-W-t) töö valemist \@ref(eq:W-via-E-Q) leheküljel`r render_pageref("eq:W-via-E-Q")`:

```{=latex}
\begin{align}
P := \frac{\mathrm{d}(E \cdot Q)}{\mathrm{d}(t)}.(\#eq:P-via-E-Q-t) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{I \cdot T^3} \cdot I \cdot T}{T} = \frac{L^2 \cdot M \cdot I \cdot T}{I \cdot T^3 \cdot T} = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-via-E-Q-t)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^3} = \frac{N \cdot m}{s} = \frac{J}{s} = W$.

Asendan valemisse \@ref(eq:P-via-E-Q-t) voolutugevuse valemist \@ref(eq:I) leheküljel`r render_pageref("eq:I")`:

```{=latex}
\begin{align}
P := E \cdot I.(\#eq:P-via-E-I) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L^2 \cdot M}{I \cdot T^3} \cdot I = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-via-E-I)
\end{align}
```

millest johtuvalt on ühik $\frac{m^2 \cdot kg}{s^3} = \frac{N \cdot m}{s} = \frac{J}{s} = W$.

Asendan valemisse \@ref(eq:P-via-E-I) voolutugevuse valemist \@ref(eq:I-E-R) leheküljel`r render_pageref("eq:I-E-R")`:

```{=latex}
\begin{align}
P := E \cdot \frac{E}{R + R_\mathrm{sisemine}} = \frac{E^2}{R + R_\mathrm{sisemine}}. (\#eq:P-via-E-R)
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{(\frac{L^2 \cdot M}{I \cdot T^3})^2}{\frac{L^2 \cdot M}{T^3 \cdot I^2}} = \frac{L^4 \cdot M^2 \cdot T^3 \cdot I^2}{I^2 \cdot T^6 \cdot L^2 \cdot M} = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-via-E-R)
\end{align}
```

millest johtuvalt on ühik $\frac{m^2 \cdot kg}{s^3} = \frac{N \cdot m}{s} = \frac{J}{s} = W$.

Elektri energia tarbija jaoks ehk kasulik võimsus:

```{=latex}
\begin{align}
P := U \cdot I (\#eq:P) 
\end{align}

```

`r render_with_emojis("((ref:haynes-2014-crc), p. 2-2)")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{L^2 \cdot M}{I \cdot T^3} \cdot I = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^3}$ või lühemalt $\frac{m \cdot N}{s}$ või kõige lühemalt $W$.

Asendades valemisse \@ref(eq:P) pinge valemist \@ref(eq:R) leheküljel`r render_pageref("eq:R")`, on elektri energia avaldatav takistuse ja voolutugevuse kaudu:

```{=latex}
\begin{align}
P := U \cdot I = (I \cdot R) \cdot I = I^2 \cdot R. (\#eq:P-I-R) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{I^2 \cdot \frac{L^2 \cdot M}{T^3 \cdot I^2} = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-I-R)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^3}$ või lühemalt $\frac{m \cdot N}{s}$ või kõige lühemalt $W$.

Asendades valemis \@ref(eq:P-I-R) elektrivoolu valemist \@ref(eq:I-E-R) leheküljel`r render_pageref("eq:I-E-R")`, saab avaldada elektri energia voolutugevuse, takistuste ja elektromotoorjõu kaudu:

```{=latex}
\begin{align}
P := (\frac{E}{R + R_\mathrm{sisemine}})^2 \cdot R = \frac{E^2 \cdot R}{(R + R_\mathrm{sisemine})^2}. (\#eq:P-E-R) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{(\frac{L^2 \cdot M}{T^3 \cdot I})^2 \cdot \frac{L^2 \cdot M}{T^3 \cdot I^2}}{(\frac{L^2 \cdot M}{T^3 \cdot I^2})^2} = \frac{(\frac{L^2 \cdot M}{T^3 \cdot I})^2}{\frac{L^2 \cdot M}{T^3 \cdot I^2}} = \frac{L^2 \cdot M}{T^3}},
(\#eq:dimensional-analysis-for-P-E-R)
\end{align}
```

mistõttu ühik on $\frac{m^2 \cdot kg}{s^3}$ või lühemalt $\frac{m \cdot N}{s}$ või kõige lühemalt $W$.

## Vooluallika kasutegur

Vooluallika kasutegur
: vooluallika kasuliku ja koguvõimsuse suhe.

```{=latex}
\begin{align}
\eta := \frac{P_\mathrm{kasulik}}{P} (\#eq:eta) 
\end{align}

```

`r render_with_emojis("((ref:cleverlysmartcom-2022-physics))")`. Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{T^3}}{\frac{L^2 \cdot M}{T^3}} = 1},
(\#eq:dimensional-analysis-for-eta)
\end{align}
```

mistõttu ühik on 1.

Asendan valemisse \@ref(eq:eta) kasuliku võimsuse valemist \@ref(eq:P-E-R) leheküljel`r render_pageref("eq:P-E-R")` ja koguvõimsuse valemist \@ref(eq:P-via-E-R) leheküljel`r render_pageref("eq:P-via-E-R")`:

```{=latex}
\begin{align}
\eta := \frac{\frac{E^2 \cdot R}{(R + R_\mathrm{sisemine})^2}}{\frac{E^2}{R + R_\mathrm{sisemine}}} = \frac{R}{R + R_\mathrm{sisemine}}. (\#eq:eta-R) 
\end{align}

```

Dimensionaalanalüüs:

```{=tex}
\begin{align}
\mathrm{\frac{\frac{L^2 \cdot M}{T^3 \cdot I^2}}{\frac{L^2 \cdot M}{T^3 \cdot I^2}} = 1},
(\#eq:dimensional-analysis-for-eta-R)
\end{align}
```

mistõttu ühik on 1.
